from enum import Enum


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    OCR_COMPLETE = "OCR_COMPLETE"
    CLAUSES_SEGMENTED = "CLAUSES_SEGMENTED"
    CLASSIFIED = "CLASSIFIED"
    RISK_SCORED = "RISK_SCORED"
    FAILED = "FAILED"


class ClauseCategory(str, Enum):
    TERMINATION_EXIT = "TERMINATION_EXIT"
    PENALTY_FEES = "PENALTY_FEES"
    AUTO_RENEWAL = "AUTO_RENEWAL"
    LIABILITY_LIMITATION = "LIABILITY_LIMITATION"
    INDEMNIFICATION = "INDEMNIFICATION"
    DISPUTE_RESOLUTION = "DISPUTE_RESOLUTION"
    GOVERNING_LAW = "GOVERNING_LAW"
    DATA_PRIVACY = "DATA_PRIVACY"
    DEPOSIT_REFUNDS = "DEPOSIT_REFUNDS"
    AMENDMENT_RIGHTS = "AMENDMENT_RIGHTS"
    PAYMENT_TERMS = "PAYMENT_TERMS"
    CONFIDENTIALITY = "CONFIDENTIALITY"
    INTELLECTUAL_PROPERTY = "INTELLECTUAL_PROPERTY"
    WARRANTIES_DISCLAIMERS = "WARRANTIES_DISCLAIMERS"
    FORCE_MAJEURE = "FORCE_MAJEURE"
    NON_COMPETE_RESTRICTION = "NON_COMPETE_RESTRICTION"
    REPRESENTATIONS = "REPRESENTATIONS"
    INSURANCE = "INSURANCE"
    OTHER = "OTHER"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RiskFlagType(str, Enum):
    UNFAIR_TERM = "UNFAIR_TERM"
    ONE_SIDED = "ONE_SIDED"
    AMBIGUOUS = "AMBIGUOUS"
    FAIR = "FAIR"
