from enum import Enum


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    OCR_COMPLETE = "OCR_COMPLETE"
    CLAUSES_SEGMENTED = "CLAUSES_SEGMENTED"
    CLASSIFIED = "CLASSIFIED"
    FAILED = "FAILED"


class ClauseCategory(str, Enum):
    PAYMENT = "PAYMENT"
    TERMINATION = "TERMINATION"
    LIABILITY_LIMITATION = "LIABILITY_LIMITATION"
    INDEMNIFICATION = "INDEMNIFICATION"
    CONFIDENTIALITY = "CONFIDENTIALITY"
    DISPUTE_RESOLUTION = "DISPUTE_RESOLUTION"
    GOVERNING_LAW = "GOVERNING_LAW"
    FORCE_MAJEURE = "FORCE_MAJEURE"
    INTELLECTUAL_PROPERTY = "INTELLECTUAL_PROPERTY"
    WARRANTY = "WARRANTY"
    ASSIGNMENT = "ASSIGNMENT"
    DEFINITIONS = "DEFINITIONS"
    TERM_AND_RENEWAL = "TERM_AND_RENEWAL"
    NOTICE = "NOTICE"
    AMENDMENT = "AMENDMENT"
    SEVERABILITY = "SEVERABILITY"
    ENTIRE_AGREEMENT = "ENTIRE_AGREEMENT"
    RECITALS = "RECITALS"
    OTHER = "OTHER"
