"""add unique document hash

Revision ID: 37b909f99365
Revises: 0286e1b9bbb2
Create Date: 2026-08-08 19:39:50.399857

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37b909f99365'
down_revision: str | Sequence[str] | None = '0286e1b9bbb2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    # ### end Alembic commands ###
